apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ctdk8sinventorytracker-pdb
  namespace: {{ .Values.namespace }}

spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: ctdk8sinventorytracker
