apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::326095712541:role/ct-aws-docker-k8s-dev-inventory-app-irsa-role
